spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev}
  data:
    mongodb:
      repositories:
        type: imperative
      authentication-database: admin
      auto-index-creation: true
      database: mongodb
      username: username
      password: password
      port: 27017
      host: localhost
      #      gridfs:
      #        bucket: storagedb
      #        database: storage

grpc:
  client:
    ping-pong-client:
      address: 'static://127.0.0.1:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

resilience4j.retry:
  instances:
    pingRetry:
      max-attempts: 5
      waitDuration: 1000ms
      retryExceptions:
        - io.grpc.StatusRuntimeException


logging:
  level:
    io.confluent.kafka.serializers: OFF
