spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:dev}
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      database: mongodb
      username: username
      password: password
      port: 27017
      host: localhost
      #      gridfs:
      #        bucket: storagedb
      #        database: storage


grpc:
  client:
    grpc-client:
      address: 'static://127.0.0.1:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
