// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package org.wsd.app.proto;

public interface OrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderName = 1;</code>
   * @return The orderName.
   */
  String getOrderName();
  /**
   * <code>string orderName = 1;</code>
   * @return The bytes for orderName.
   */
  com.google.protobuf.ByteString
      getOrderNameBytes();

  /**
   * <code>int32 orderPrice = 2;</code>
   * @return The orderPrice.
   */
  int getOrderPrice();
}
