// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: schema.proto

package org.wsd.app.proto;

public final class Schema {
  private Schema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014schema.proto\"\037\n\014OrderRequest\022\017\n\007orderI" +
      "d\030\001 \001(\005\"6\n\rOrderResponse\022\021\n\torderName\030\001 " +
      "\001(\t\022\022\n\norderPrice\030\002 \001(\0052\206\002\n\014OrderService" +
      "\022+\n\010GetOrder\022\r.OrderRequest\032\016.OrderRespo" +
      "nse\"\000\022@\n\033GetServerSideOrderStreaming\022\r.O" +
      "rderRequest\032\016.OrderResponse\"\0000\001\022@\n\033GetCl" +
      "ientSideOrderStreaming\022\r.OrderRequest\032\016." +
      "OrderResponse\"\000(\001\022E\n\036GetBiDirectionalOrd" +
      "erStreaming\022\r.OrderRequest\032\016.OrderRespon" +
      "se\"\000(\0010\001B\025\n\021org.wsd.app.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderRequest_descriptor,
        new String[] { "OrderId", });
    internal_static_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderResponse_descriptor,
        new String[] { "OrderName", "OrderPrice", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
