/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.wsd.app.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SensorEventAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 394710158259602094L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SensorEventAvro\",\"namespace\":\"org.wsd.app.event\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"x\",\"type\":\"double\"},{\"name\":\"y\",\"type\":\"double\",\"default\":-1.0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SensorEventAvro> ENCODER =
      new BinaryMessageEncoder<SensorEventAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SensorEventAvro> DECODER =
      new BinaryMessageDecoder<SensorEventAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SensorEventAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SensorEventAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SensorEventAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SensorEventAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SensorEventAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SensorEventAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SensorEventAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SensorEventAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private double x;
   private double y;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SensorEventAvro() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param x The new value for x
   * @param y The new value for y
   */
  public SensorEventAvro(java.lang.CharSequence id, java.lang.Double x, java.lang.Double y) {
    this.id = id;
    this.x = x;
    this.y = y;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return x;
    case 2: return y;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: x = (java.lang.Double)value$; break;
    case 2: y = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'x' field.
   * @return The value of the 'x' field.
   */
  public double getX() {
    return x;
  }


  /**
   * Sets the value of the 'x' field.
   * @param value the value to set.
   */
  public void setX(double value) {
    this.x = value;
  }

  /**
   * Gets the value of the 'y' field.
   * @return The value of the 'y' field.
   */
  public double getY() {
    return y;
  }


  /**
   * Sets the value of the 'y' field.
   * @param value the value to set.
   */
  public void setY(double value) {
    this.y = value;
  }

  /**
   * Creates a new SensorEventAvro RecordBuilder.
   * @return A new SensorEventAvro RecordBuilder
   */
  public static org.wsd.app.event.SensorEventAvro.Builder newBuilder() {
    return new org.wsd.app.event.SensorEventAvro.Builder();
  }

  /**
   * Creates a new SensorEventAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SensorEventAvro RecordBuilder
   */
  public static org.wsd.app.event.SensorEventAvro.Builder newBuilder(org.wsd.app.event.SensorEventAvro.Builder other) {
    if (other == null) {
      return new org.wsd.app.event.SensorEventAvro.Builder();
    } else {
      return new org.wsd.app.event.SensorEventAvro.Builder(other);
    }
  }

  /**
   * Creates a new SensorEventAvro RecordBuilder by copying an existing SensorEventAvro instance.
   * @param other The existing instance to copy.
   * @return A new SensorEventAvro RecordBuilder
   */
  public static org.wsd.app.event.SensorEventAvro.Builder newBuilder(org.wsd.app.event.SensorEventAvro other) {
    if (other == null) {
      return new org.wsd.app.event.SensorEventAvro.Builder();
    } else {
      return new org.wsd.app.event.SensorEventAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for SensorEventAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SensorEventAvro>
    implements org.apache.avro.data.RecordBuilder<SensorEventAvro> {

    private java.lang.CharSequence id;
    private double x;
    private double y;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.wsd.app.event.SensorEventAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.x)) {
        this.x = data().deepCopy(fields()[1].schema(), other.x);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.y)) {
        this.y = data().deepCopy(fields()[2].schema(), other.y);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing SensorEventAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(org.wsd.app.event.SensorEventAvro other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.x)) {
        this.x = data().deepCopy(fields()[1].schema(), other.x);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.y)) {
        this.y = data().deepCopy(fields()[2].schema(), other.y);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.wsd.app.event.SensorEventAvro.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.wsd.app.event.SensorEventAvro.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'x' field.
      * @return The value.
      */
    public double getX() {
      return x;
    }


    /**
      * Sets the value of the 'x' field.
      * @param value The value of 'x'.
      * @return This builder.
      */
    public org.wsd.app.event.SensorEventAvro.Builder setX(double value) {
      validate(fields()[1], value);
      this.x = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'x' field has been set.
      * @return True if the 'x' field has been set, false otherwise.
      */
    public boolean hasX() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'x' field.
      * @return This builder.
      */
    public org.wsd.app.event.SensorEventAvro.Builder clearX() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'y' field.
      * @return The value.
      */
    public double getY() {
      return y;
    }


    /**
      * Sets the value of the 'y' field.
      * @param value The value of 'y'.
      * @return This builder.
      */
    public org.wsd.app.event.SensorEventAvro.Builder setY(double value) {
      validate(fields()[2], value);
      this.y = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'y' field has been set.
      * @return True if the 'y' field has been set, false otherwise.
      */
    public boolean hasY() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'y' field.
      * @return This builder.
      */
    public org.wsd.app.event.SensorEventAvro.Builder clearY() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SensorEventAvro build() {
      try {
        SensorEventAvro record = new SensorEventAvro();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.x = fieldSetFlags()[1] ? this.x : (java.lang.Double) defaultValue(fields()[1]);
        record.y = fieldSetFlags()[2] ? this.y : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SensorEventAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<SensorEventAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SensorEventAvro>
    READER$ = (org.apache.avro.io.DatumReader<SensorEventAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeDouble(this.x);

    out.writeDouble(this.y);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.x = in.readDouble();

      this.y = in.readDouble();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.x = in.readDouble();
          break;

        case 2:
          this.y = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










